// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'buttonContained': string;
  'buttonOutlined': string;
}
export const cssExports: CssExports;
export default cssExports;
