name: Build and Deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - "server/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    environment:
      name: production

    env:
      NODE_ENV: development

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Dependencies for kate-state
        run: cd kate-state && npm ci

      - name: Run tests kate-state
        run: cd kate-state && npm run test

      - name: Build kate-state
        run: cd kate-state && npm run build

      - name: Install Dependencies for sample-app
        run: cd sample-app && npm ci

      - name: Run tests sample-app
        run: cd sample-app && npm run test

      - name: Set NODE_ENV to production
        run: |
          echo "NODE_ENV=production" >> $GITHUB_ENV
          echo "REACT_APP_RAPID_API_KEY=${{ secrets.REACT_APP_RAPID_API_KEY }}" >> $GITHUB_ENV

      - name: Build sample-app
        run: cd sample-app && npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES_PAT }}
          publish_dir: ./sample-app/dist
